# Generated by Django 5.0.1 on 2024-03-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_doctor_signup_doctors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='username',
        ),
    ]
