# Generated by Django 5.0.1 on 2024-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_doctors_password_remove_doctors_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=20),
        ),
    ]
