# Generated by Django 5.0.1 on 2024-03-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_patients_gender_alter_patients_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
