# Generated by Django 5.0.1 on 2024-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doc_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pat_Id', models.BigIntegerField()),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Pat_Register',
            },
        ),
    ]
