# Generated by Django 5.0.1 on 2024-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_pat_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(choices=[('Opthalmology', 'Opthalmology'), ('Orthopedics', 'Orthopedics'), ('Gastroenterology', 'Gastroenterology'), ('Cardiology', 'Cardiology'), ('Gynecology', 'Gynecology'), ('ENT', 'Ent'), ('Dentistry', 'Dentistry'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('General', 'General'), ('Pediatrics', 'Pediatrics')], default='General', max_length=100),
        ),
    ]
