# Generated by Django 5.0.1 on 2024-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_adm_register_remove_doc_register_doc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='speciality',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='consultation_area',
            new_name='Department',
        ),
        migrations.AlterField(
            model_name='patients',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
