# Generated by Django 5.0.1 on 2024-03-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_rename_speciality_doctors_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pat_register',
            name='Pat_Id',
        ),
    ]
