# Generated by Django 5.0.1 on 2024-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_pat_register_pat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
